# Generated by Django 5.2.7 on 2025-10-12 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='Edad del cliente', validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(98)])),
                ('job', models.CharField(help_text='Ocupación del cliente', max_length=50)),
                ('marital', models.CharField(help_text='Estado civil', max_length=20)),
                ('education', models.CharField(help_text='Nivel educativo', max_length=50)),
                ('default', models.BooleanField(help_text='¿Crédito en demora?')),
                ('balance', models.IntegerField(help_text='Balance promedio anual en euros')),
                ('housing', models.BooleanField(help_text='¿Tiene préstamo hipotecario?')),
                ('loan', models.BooleanField(help_text='¿Tiene préstamo personal?')),
                ('contact', models.CharField(help_text='Tipo de contacto', max_length=20)),
                ('day', models.IntegerField(help_text='Día del último contacto', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('month', models.CharField(help_text='Mes del último contacto', max_length=10)),
                ('duration', models.IntegerField(help_text='Duración del último contacto en segundos', validators=[django.core.validators.MinValueValidator(0)])),
                ('campaign', models.IntegerField(help_text='Número de contactos en esta campaña', validators=[django.core.validators.MinValueValidator(1)])),
                ('pdays', models.IntegerField(help_text='Días desde el último contacto previo (-1 si no fue contactado)')),
                ('previous', models.IntegerField(help_text='Número de contactos previos a esta campaña', validators=[django.core.validators.MinValueValidator(0)])),
                ('poutcome', models.CharField(help_text='Resultado de la campaña previa', max_length=20)),
                ('y', models.BooleanField(help_text='¿El cliente suscribió un depósito a plazo?')),
            ],
            options={
                'verbose_name': 'Registro de Campaña',
                'verbose_name_plural': 'Registros de Campañas',
            },
        ),
    ]
