# Generated by Django 5.2.7 on 2025-10-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para el conjunto de filtros', max_length=100)),
                ('parameters', models.JSONField(help_text='Parámetros del filtro guardados como un objeto JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Filtro Guardado',
                'verbose_name_plural': 'Filtros Guardados',
                'ordering': ['-created_at'],
            },
        ),
    ]
