# Generated by Django 5.2.7 on 2025-10-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('records_count', models.IntegerField(verbose_name='Registros Afectados')),
                ('filters_applied', models.JSONField(blank=True, null=True, verbose_name='Filtros Aplicados (JSON)')),
                ('saved_filter_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Filtro Guardado')),
            ],
            options={
                'verbose_name': 'Historial de Consulta',
                'verbose_name_plural': 'Historial de Consultas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
